/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    suppliers: Supplier;
    reviews: Review;
    'stripe-events': StripeEvent;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'stripe-events': StripeEventsSelect<false> | StripeEventsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
    company: Company;
    'brand-settings': BrandSetting;
    'merchant-center': MerchantCenter;
    'stripe-settings': StripeSetting;
    analytics: Analytics;
    'email-settings': EmailSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
    'brand-settings': BrandSettingsSelect<false> | BrandSettingsSelect<true>;
    'merchant-center': MerchantCenterSelect<false> | MerchantCenterSelect<true>;
    'stripe-settings': StripeSettingsSelect<false> | StripeSettingsSelect<true>;
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>;
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  /**
   * Computed from payment status and tracking — not editable.
   */
  fulfilmentStatus?: ('needs_shipment' | 'shipped' | 'completed' | 'cancelled' | 'refunded') | null;
  accessToken?: string | null;
  /**
   * Saving a new value emails the customer their tracking link.
   */
  trackingNumber?: string | null;
  carrier?: ('usps' | 'ups' | 'fedex' | 'dhl' | 'dpd' | 'other') | null;
  /**
   * Stamped when a tracking number is first saved.
   */
  shippedAt?: string | null;
  confirmationEmailSentAt?: string | null;
  trackingEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  /**
   * Was-price in CENTS, shown struck through. Must be a genuine price this product was recently offered at (FTC / CA 90-day rule). Cleared automatically unless greater than the current price.
   */
  compareAtPriceInUSD?: number | null;
  /**
   * Optional. Shown as honest urgency and sent to Google as the sale window end. If set, the price must actually revert then.
   */
  saleEndsAt?: string | null;
  /**
   * Stamped automatically when the sale began — reference-pricing provenance.
   */
  saleStartedAt?: string | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * One or two sentences shown directly under the title, next to the buy button. Lead with the benefit, not the feature.
   */
  shortDescription?: string | null;
  /**
   * The scannable layer people actually read before the full description. 3–6 works best.
   */
  keyFeatures?:
    | {
        feature: string;
        /**
         * Optional supporting clause.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as a table in tabular figures. This is what electronics buyers compare on, and what stops a pre-sales email.
   */
  specifications?:
    | {
        label: string;
        value: string;
        /**
         * Optional heading, e.g. "Dimensions".
         */
        group?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Prevents "where is the cable" support tickets, and the returns that follow them.
   */
  inTheBox?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kitchenware and outdoor especially — care detail signals quality.
   */
  careInstructions?: string | null;
  /**
   * Shown near the buy button. Expected at this price point; leave blank to fall back to the shop default.
   */
  warrantyMonths?: number | null;
  /**
   * 30 days is the US baseline expectation. 15% of shoppers abandon over an unsatisfactory return policy, and 60% look for it on the product page.
   */
  returnWindowDays?: number | null;
  /**
   * Unexpected shipping cost is the single biggest cause of checkout abandonment (39%). Say so before the cart, not in it.
   */
  freeShippingEligible?: boolean | null;
  /**
   * Grams. Required for real shipping rates.
   */
  weightGrams?: number | null;
  shippingClass?: ('standard' | 'oversized' | 'fragile' | 'hazardous') | null;
  lengthMm?: number | null;
  widthMm?: number | null;
  heightMm?: number | null;
  /**
   * What you get, e.g. "500ml", "2kg", "12 pack".
   */
  unitPricingMeasure?: string | null;
  /**
   * What to price against, e.g. "100ml". Yields "$0.74 per 100ml".
   */
  unitPricingBaseMeasure?: string | null;
  /**
   * Direct and dropship are both sold by us, so both can be advertised. Affiliate sends the customer off-site and is permanently excluded from the Google feed.
   */
  fulfilment: 'direct' | 'dropship' | 'affiliate';
  /**
   * Derived from fulfilment — cannot be set by hand. Affiliate products are never eligible.
   */
  feedEligible?: boolean | null;
  supplier?: (number | null) | Supplier;
  /**
   * The supplier’s own identifier, used when routing the purchase order.
   */
  supplierSku?: string | null;
  /**
   * What we pay the supplier, in MINOR units (cents). Never a float. Used for margin reporting, never exposed publicly.
   */
  supplierCost?: number | null;
  /**
   * Overrides the supplier default for this product only. Leave blank to inherit.
   */
  leadTimeDaysOverride?: number | null;
  /**
   * Outbound checkout URL. Rendered with rel="sponsored" and a visible disclosure — required by EU consumer law independently of Google.
   */
  affiliateUrl?: string | null;
  affiliateNetwork?: string | null;
  /**
   * Affiliate prices drift. Stale prices mislead customers and hurt trust.
   */
  affiliateLastVerifiedAt?: string | null;
  /**
   * Required unless the product genuinely has no brand.
   */
  brand?: string | null;
  condition?: ('new' | 'refurbished' | 'used') | null;
  /**
   * EAN/UPC/ISBN. Strongly improves Shopping performance — Google matches offers across merchants on GTIN.
   */
  gtin?: string | null;
  /**
   * Manufacturer part number. Use when no GTIN exists.
   */
  mpn?: string | null;
  /**
   * Google’s taxonomy ID, e.g. 2271. Required for some verticals and improves matching everywhere.
   */
  googleProductCategory?: string | null;
  /**
   * Shared by every variant of the same product family. Products with the same value link to each other as colour/size options. Leave empty for standalone products.
   */
  itemGroupId?: string | null;
  /**
   * What makes THIS sibling different, e.g. “Cream / 32 Quarts”. Shown on the family selector.
   */
  variantLabel?: string | null;
  /**
   * Feed attribute. This sibling’s colour, e.g. “Empire Red”.
   */
  color?: string | null;
  /**
   * Feed attribute. Size or capacity, e.g. “7 quarts” — Google has no capacity attribute, size carries it.
   */
  size?: string | null;
  /**
   * Manually hold an otherwise-eligible product back from the feed (e.g. pending imagery or a policy review).
   */
  excludeFromFeed?: boolean | null;
  feedExclusionReason?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  categories?: (number | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Derived from approved reviews. Blank when there are none.
   */
  ratingAverage?: number | null;
  ratingCount?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | ContactDetailsBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactDetailsBlock".
 */
export interface ContactDetailsBlock {
  /**
   * Optional. Defaults to “Other ways to reach us”.
   */
  heading?: string | null;
  /**
   * Optional line above the details.
   */
  intro?: string | null;
  /**
   * Include the returns address. Useful on a contact page — people look for it here as often as on the returns policy.
   */
  showReturnsAddress?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactDetails';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Leave blank for a top-level category. Only two levels are supported.
   */
  parent?: (number | null) | Category;
  /**
   * Shown at the top of the category page. Worth writing — a category page with real copy ranks; one with a bare product grid does not.
   */
  description?: string | null;
  /**
   * Used for visual category navigation on the homepage and in the mega-menu.
   */
  image?: (number | null) | Media;
  /**
   * Uncheck to keep a category reachable by URL but out of the menu.
   */
  showInNav?: boolean | null;
  /**
   * Lower sorts first. Ties fall back to alphabetical.
   */
  navOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  /**
   * Pausing a supplier does not unpublish its products — handle stock via inventory sync.
   */
  status: 'active' | 'paused';
  /**
   * Business days from order to dispatch. Feeds Merchant Center transit time — understating this causes policy issues.
   */
  defaultLeadTimeDays: number;
  /**
   * Maps to the Merchant Center shipping_label attribute, so per-supplier shipping rates can be configured in Merchant Center.
   */
  shippingLabel?: string | null;
  /**
   * EU consumer law minimum is 14 days for distance selling.
   */
  returnWindowDays?: number | null;
  /**
   * ISO 3166-1 alpha-2, e.g. LT. Affects delivery estimates and customs messaging.
   */
  shipsFromCountry?: string | null;
  integration: 'manual' | 'csv' | 'api';
  /**
   * URL of the supplier product/stock feed, polled on a schedule.
   */
  feedUrl?: string | null;
  apiBaseUrl?: string | null;
  /**
   * NAME of the env var holding this supplier’s API key — never the key itself. Secrets do not belong in the database.
   */
  credentialsEnvVar?: string | null;
  lastSyncedAt?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  /**
   * Where purchase orders are sent when integration is manual.
   */
  orderRoutingEmail?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
    checkoutSessionID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  /**
   * Where this order ships. Copied from the payment on creation — metadata is not a database.
   */
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    /**
     * ISO 3166-1 alpha-2 (e.g. LT). Stripe rejects anything else.
     */
    country?: string | null;
    phone?: string | null;
    title?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country: 'US';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Optional. Products with no reviews render no review UI at all.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  /**
   * Only approved reviews are public or counted in the average.
   */
  status: 'pending' | 'approved' | 'rejected';
  rating: number;
  /**
   * Materially changes how much trust a review earns. Shown as a badge.
   */
  verifiedPurchase?: boolean | null;
  title?: string | null;
  body: string;
  authorName: string;
  /**
   * Optional, e.g. "Portland, OR".
   */
  authorLocation?: string | null;
  /**
   * Buyers treat customer photos as objective evidence in a way they never treat ours. 63% of sites make these hard to browse.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Which option they bought, e.g. "10 inch / Copper".
   */
  variantPurchased?: string | null;
  /**
   * 89% of sites never answer negative reviews. A visible, non-defensive reply measurably improves confidence — including for the people reading the complaint.
   */
  merchantResponse?: string | null;
  helpfulCount?: number | null;
  /**
   * Only for imported reviews. Preserve the original date — re-dating imports to the import day destroys the recency signal that makes reviews trustworthy.
   */
  originalCreatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every Stripe webhook event received. Read-only — written by the webhook pipeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events".
 */
export interface StripeEvent {
  id: number;
  eventId: string;
  type: string;
  status: 'received' | 'processed' | 'ignored' | 'failed';
  /**
   * False for test-mode events.
   */
  livemode?: boolean | null;
  error?: string | null;
  /**
   * What the handler did.
   */
  notes?: string | null;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'stripe-events';
        value: number | StripeEvent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        contactDetails?: T | ContactDetailsBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactDetailsBlock_select".
 */
export interface ContactDetailsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  showReturnsAddress?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  description?: T;
  image?: T;
  showInNav?: T;
  navOrder?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  defaultLeadTimeDays?: T;
  shippingLabel?: T;
  returnWindowDays?: T;
  shipsFromCountry?: T;
  integration?: T;
  feedUrl?: T;
  apiBaseUrl?: T;
  credentialsEnvVar?: T;
  lastSyncedAt?: T;
  contactName?: T;
  contactEmail?: T;
  orderRoutingEmail?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  status?: T;
  rating?: T;
  verifiedPurchase?: T;
  title?: T;
  body?: T;
  authorName?: T;
  authorLocation?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  variantPurchased?: T;
  merchantResponse?: T;
  helpfulCount?: T;
  originalCreatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events_select".
 */
export interface StripeEventsSelect<T extends boolean = true> {
  eventId?: T;
  type?: T;
  status?: T;
  livemode?: T;
  error?: T;
  notes?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  compareAtPriceInUSD?: T;
  saleEndsAt?: T;
  saleStartedAt?: T;
  relatedProducts?: T;
  shortDescription?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        detail?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        group?: T;
        id?: T;
      };
  inTheBox?:
    | T
    | {
        item?: T;
        id?: T;
      };
  careInstructions?: T;
  warrantyMonths?: T;
  returnWindowDays?: T;
  freeShippingEligible?: T;
  weightGrams?: T;
  shippingClass?: T;
  lengthMm?: T;
  widthMm?: T;
  heightMm?: T;
  unitPricingMeasure?: T;
  unitPricingBaseMeasure?: T;
  fulfilment?: T;
  feedEligible?: T;
  supplier?: T;
  supplierSku?: T;
  supplierCost?: T;
  leadTimeDaysOverride?: T;
  affiliateUrl?: T;
  affiliateNetwork?: T;
  affiliateLastVerifiedAt?: T;
  brand?: T;
  condition?: T;
  gtin?: T;
  mpn?: T;
  googleProductCategory?: T;
  itemGroupId?: T;
  variantLabel?: T;
  color?: T;
  size?: T;
  excludeFromFeed?: T;
  feedExclusionReason?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  ratingAverage?: T;
  ratingCount?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  fulfilmentStatus?: T;
  accessToken?: T;
  trackingNumber?: T;
  carrier?: T;
  shippedAt?: T;
  confirmationEmailSentAt?: T;
  trackingEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
        checkoutSessionID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero copy and what the homepage features.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Small line above the headline. Defaults to the company name. Keep it under ~30 characters.
   */
  eyebrow?: string | null;
  /**
   * The one thing a first-time visitor should take away. Defaults to the company tagline. Six to ten words works best — it is set large, and a long headline stops being a headline.
   */
  headline?: string | null;
  /**
   * One or two sentences supporting the headline. Say what makes the range worth buying, not what the category is.
   */
  subcopy?: string | null;
  /**
   * Defaults to “Shop all”.
   */
  primaryCtaLabel?: string | null;
  /**
   * Defaults to /shop.
   */
  primaryCtaHref?: string | null;
  /**
   * Optional. Hidden when blank.
   */
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Shown large in the hero. Pick something with strong photography — it is the first product anyone sees. Falls back to the newest product.
   */
  heroProduct?: (number | null) | Product;
  /**
   * The “Featured” row. Leave empty to fall back to the newest products.
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Defaults to “Featured”.
   */
  featuredHeading?: string | null;
  /**
   * Order and selection for the category grid. Leave empty to use the top-level categories in menu order.
   */
  featuredCategories?: (number | Category)[] | null;
  showCategories?: boolean | null;
  showFeatured?: boolean | null;
  /**
   * Returns, shipping and warranty. Worth keeping on — at higher price points the blocker is risk rather than price.
   */
  showTrustRow?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Used sitewide — header, footer, contact, returns and terms pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  /**
   * Trading name. Appears in the header, footer, emails and page titles.
   */
  name: string;
  /**
   * Registered entity, e.g. "Acme Housewares LLC". Used in terms and conditions where the trading name is not sufficient. Falls back to the trading name.
   */
  legalName?: string | null;
  /**
   * Text shown next to the logo mark in the header, e.g. "yourshop.com". Falls back to the trading name. Header only — titles and emails keep using the trading name.
   */
  brandWordmark?: string | null;
  tagline?: string | null;
  /**
   * Used for the copyright range in the footer.
   */
  foundedYear?: number | null;
  /**
   * Shown on LIGHT backgrounds — so this is usually the dark version of your mark. SVG preferred.
   */
  logoLight?: (number | null) | Media;
  /**
   * Shown on DARK backgrounds. Leave blank to reuse the light logo inverted.
   */
  logoDark?: (number | null) | Media;
  /**
   * Square icon for favicons and tight spaces.
   */
  logoMark?: (number | null) | Media;
  /**
   * Rendered height in the header, in pixels.
   */
  logoHeight?: number | null;
  /**
   * Social sharing image, 1200×630.
   */
  ogImage?: (number | null) | Media;
  email?: string | null;
  /**
   * Falls back to the general email.
   */
  supportEmail?: string | null;
  phone?: string | null;
  /**
   * e.g. "Mon–Fri, 9am–5pm ET".
   */
  supportHours?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  /**
   * State / province.
   */
  region?: string | null;
  postalCode?: string | null;
  /**
   * ISO 3166-1 alpha-2, e.g. US.
   */
  country?: string | null;
  /**
   * Uncheck to use a separate returns address — a US facility, a 3PL, or a supplier.
   */
  returnsAddressSameAsAbove?: boolean | null;
  returnsLocation?: {
    /**
     * Who the parcel is addressed to, e.g. “Acme Returns Dept”. Not always the company name — a 3PL will have its own.
     */
    recipient?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    /**
     * State / province.
     */
    region?: string | null;
    postalCode?: string | null;
    /**
     * ISO 3166-1 alpha-2, e.g. US.
     */
    country?: string | null;
    /**
     * Optional. Some carriers require one on the label.
     */
    phone?: string | null;
    /**
     * Anything the customer must do — e.g. “Write your RMA number on the outside of the parcel.” Shown with the address on the returns page.
     */
    instructions?: string | null;
  };
  companyNumber?: string | null;
  /**
   * VAT number, EIN, etc.
   */
  taxId?: string | null;
  /**
   * Governing law for the terms, e.g. "the State of Delaware, USA". Do not leave this generic — it is the clause that decides where disputes are heard.
   */
  jurisdiction?: string | null;
  /**
   * 30 days is the US baseline expectation.
   */
  returnWindowDays?: number | null;
  /**
   * Used when a product does not specify its own.
   */
  defaultWarrantyMonths?: number | null;
  /**
   * In MINOR units (cents). Blank means free shipping always.
   */
  freeShippingThreshold?: number | null;
  /**
   * Business days before dispatch.
   */
  processingTimeDays?: number | null;
  /**
   * Free returns materially reduce hesitation on high-value orders — 15% of shoppers abandon over an unsatisfactory return policy.
   */
  returnsShippingPaidBy?: ('merchant' | 'customer') | null;
  /**
   * Master switch. When off, the disclaimer disappears from every page and the {{company.shippingDisclaimer}} placeholder resolves to nothing — no empty headings, no stray braces.
   */
  shippingDisclaimerEnabled?: boolean | null;
  /**
   * Where orders dispatch from.
   */
  shipsFrom?: string | null;
  /**
   * Primary destination market.
   */
  shipsTo?: string | null;
  /**
   * Transit days after dispatch.
   */
  deliveryMinDays?: number | null;
  /**
   * Quote the realistic upper bound. Understating delivery converts slightly better and produces support load, refunds and chargebacks.
   */
  deliveryMaxDays?: number | null;
  /**
   * The US suspended its $800 de minimis exemption for all origins in August 2025, so duties now apply to essentially every shipment regardless of value. Whoever pays them, the customer has to be told before they buy — an unexpected bill at the door is the top cause of refused deliveries and chargebacks on cross-border orders.
   */
  customsHandling?: ('ddp' | 'ddu' | 'unspecified') | null;
  /**
   * Optional. Replaces the generated sentence entirely. Leave blank to have it built from the values above, which keeps it consistent with the product page and policy pages.
   */
  shippingDisclaimerOverride?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'x' | 'youtube' | 'tiktok' | 'pinterest' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings".
 */
export interface BrandSetting {
  id: number;
  /**
   * Paste a coolors.co palette URL (e.g. coolors.co/palette/264653-2a9d8f-e9c46a-f4a261-e76f51) or a list of hex codes. 3–5 colours. Leave blank to use the default theme.
   */
  palette?: string | null;
  /**
   * Generate a dark variant. Not an inversion — chroma is reduced independently.
   */
  enableDarkMode?: boolean | null;
  /**
   * Heavy rounding reads consumer-app rather than considered-purchase.
   */
  radius?: ('0rem' | '0.25rem' | '0.75rem' | '1.5rem') | null;
  /**
   * Whitespace is the oldest signal of confidence.
   */
  density?: ('compact' | 'comfortable' | 'spacious') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchant-center".
 */
export interface MerchantCenter {
  id: number;
  /**
   * Products expire from Merchant Center after 30 days. A full refresh must run well inside that window.
   */
  lastSyncAt?: string | null;
  lastSyncStatus?: ('never' | 'success' | 'partial' | 'failed') | null;
  /**
   * Result of the most recent run.
   */
  lastSyncSummary?: string | null;
  /**
   * Master switch. While off, no scheduled sync runs — the preview below still works.
   */
  enabled?: boolean | null;
  /**
   * Build and validate payloads without sending them to Google. Leave on until a preview has been reviewed against the live catalogue.
   */
  dryRun?: boolean | null;
  /**
   * Merchant Center account ID — digits only, no "accounts/" prefix.
   */
  merchantAccountId?: string | null;
  credentials?: {
    /**
     * Write-only: paste the whole JSON key file to set or replace, reads back empty. Stored encrypted; a database dump reveals ciphertext only.
     */
    serviceAccountJson?: string | null;
    serviceAccountJsonEnc?: string | null;
    /**
     * Tick and save to erase the stored key (e.g. after rotating it).
     */
    clearStoredCredentials?: boolean | null;
  };
  /**
   * Auto-generated. Your scheduled-fetch feed URL is <your domain>/feed/google-shopping.xml?key=<this token> — add it in Merchant Center under Data sources → Add product source → Scheduled fetch. No Google credentials needed.
   */
  feedToken?: string | null;
  /**
   * Full-refresh cadence. Must stay under 30 — Google expires API-uploaded products at 30 days, so a 14-day cadence tolerates one failed run.
   */
  refreshIntervalDays?: number | null;
  /**
   * Products are keyed as contentLanguage~feedLabel~offerId, so these values are part of a product’s identity. Changing one creates new products rather than updating existing ones.
   */
  markets?:
    | {
        /**
         * e.g. LT
         */
        feedLabel: string;
        /**
         * ISO 639-1, e.g. en
         */
        contentLanguage: string;
        /**
         * ISO 4217, e.g. EUR
         */
        currencyCode: string;
        /**
         * accounts/{account}/dataSources/{id}. Must be an API-type data source — file-based sources reject API writes. Left blank until created.
         */
        dataSource?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-settings".
 */
export interface StripeSetting {
  id: number;
  /**
   * Keys are read from here first, then from environment variables. Secret values are write-only: paste to set or replace, and the field shows empty again after saving. Stored values are encrypted.
   */
  credentials?: {
    /**
     * Starts with pk_. Public by design — used by the checkout page.
     */
    publishableKey?: string | null;
    /**
     * Starts with sk_ (or rk_ for a restricted key). Write-only — pasting replaces the stored key; leaving it blank keeps it.
     */
    secretKey?: string | null;
    /**
     * Starts with whsec_. Write-only, same as the secret key. From the webhook endpoint settings in the Stripe dashboard (or `pnpm stripe-webhooks` locally).
     */
    webhookSecret?: string | null;
    /**
     * Removes the stored keys; the shop falls back to environment variables.
     */
    clearStoredCredentials?: boolean | null;
    secretKeyEnc?: string | null;
    webhookSecretEnc?: string | null;
  };
  /**
   * When off, the refund action on transactions is disabled everywhere. Useful if refunds should only ever be issued from the Stripe dashboard.
   */
  allowRefundsFromAdmin?: boolean | null;
  /**
   * How many recent transactions each reconciliation run checks. Each one is a Stripe API call, so keep this modest.
   */
  reconcileLimit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Google Analytics 4. Paste a measurement ID to enable tracking sitewide — leave empty to run without analytics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  /**
   * Looks like G-XXXXXXXXXX — Google Analytics → Admin → Data streams → your web stream. Empty disables tracking entirely (no script is loaded).
   */
  gaMeasurementId?: string | null;
  /**
   * Shows a small consent bar and wires Google Consent Mode v2: analytics/ad storage stays DENIED until the visitor accepts (Google still receives cookieless pings and models the gap). Turn off only for markets where implied consent is acceptable — the banner never renders while the measurement ID is empty either way.
   */
  cookieBannerEnabled?: boolean | null;
  /**
   * Optional. E-commerce events sent automatically: view_item, add_to_cart, remove_from_cart, view_cart, begin_checkout, purchase — visible in GA under Reports → Monetization once traffic flows.
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The shop mailbox. Sends order confirmations, tracking emails and password resets, and powers the Mail inbox in this admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  /**
   * Sender name on outgoing email. Falls back to the Company name.
   */
  fromName?: string | null;
  /**
   * Falls back to the SMTP username. Must be an address the mailbox may send as.
   */
  fromAddress?: string | null;
  /**
   * Reply-To header on all outgoing mail. Leave empty to receive replies at the From address. If you ever send as noreply@, set this to the mailbox the Mail view reads — otherwise customer replies vanish.
   */
  replyToAddress?: string | null;
  smtp?: {
    /**
     * e.g. smtp.zoho.com
     */
    host?: string | null;
    /**
     * 465 (TLS) or 587 (STARTTLS).
     */
    port?: number | null;
    /**
     * On for port 465.
     */
    secure?: boolean | null;
    username?: string | null;
    /**
     * Write-only: paste to set or replace, reads back empty. Use an APP password, not the account password.
     */
    password?: string | null;
    passwordEnc?: string | null;
  };
  imap?: {
    /**
     * Use the SMTP username/password for IMAP too (the normal case).
     */
    sameCredentials?: boolean | null;
    /**
     * e.g. imap.zoho.com. Falls back to the SMTP host.
     */
    host?: string | null;
    port?: number | null;
    /**
     * Where replies are filed.
     */
    sentFolder?: string | null;
    username?: string | null;
    /**
     * Write-only, like the SMTP password.
     */
    password?: string | null;
    passwordEnc?: string | null;
  };
  /**
   * Appended to every reply sent from the Mail view (plain text; line breaks are kept). Not added to automated order emails — those have their own template footer.
   */
  signature?: string | null;
  /**
   * Tick and save to erase the stored passwords (e.g. after rotating them).
   */
  clearStoredCredentials?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subcopy?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  heroProduct?: T;
  featuredProducts?: T;
  featuredHeading?: T;
  featuredCategories?: T;
  showCategories?: T;
  showFeatured?: T;
  showTrustRow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  brandWordmark?: T;
  tagline?: T;
  foundedYear?: T;
  logoLight?: T;
  logoDark?: T;
  logoMark?: T;
  logoHeight?: T;
  ogImage?: T;
  email?: T;
  supportEmail?: T;
  phone?: T;
  supportHours?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  region?: T;
  postalCode?: T;
  country?: T;
  returnsAddressSameAsAbove?: T;
  returnsLocation?:
    | T
    | {
        recipient?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
        instructions?: T;
      };
  companyNumber?: T;
  taxId?: T;
  jurisdiction?: T;
  returnWindowDays?: T;
  defaultWarrantyMonths?: T;
  freeShippingThreshold?: T;
  processingTimeDays?: T;
  returnsShippingPaidBy?: T;
  shippingDisclaimerEnabled?: T;
  shipsFrom?: T;
  shipsTo?: T;
  deliveryMinDays?: T;
  deliveryMaxDays?: T;
  customsHandling?: T;
  shippingDisclaimerOverride?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-settings_select".
 */
export interface BrandSettingsSelect<T extends boolean = true> {
  palette?: T;
  enableDarkMode?: T;
  radius?: T;
  density?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merchant-center_select".
 */
export interface MerchantCenterSelect<T extends boolean = true> {
  lastSyncAt?: T;
  lastSyncStatus?: T;
  lastSyncSummary?: T;
  enabled?: T;
  dryRun?: T;
  merchantAccountId?: T;
  credentials?:
    | T
    | {
        serviceAccountJson?: T;
        serviceAccountJsonEnc?: T;
        clearStoredCredentials?: T;
      };
  feedToken?: T;
  refreshIntervalDays?: T;
  markets?:
    | T
    | {
        feedLabel?: T;
        contentLanguage?: T;
        currencyCode?: T;
        dataSource?: T;
        active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-settings_select".
 */
export interface StripeSettingsSelect<T extends boolean = true> {
  credentials?:
    | T
    | {
        publishableKey?: T;
        secretKey?: T;
        webhookSecret?: T;
        clearStoredCredentials?: T;
        secretKeyEnc?: T;
        webhookSecretEnc?: T;
      };
  allowRefundsFromAdmin?: T;
  reconcileLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  gaMeasurementId?: T;
  cookieBannerEnabled?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  fromName?: T;
  fromAddress?: T;
  replyToAddress?: T;
  smtp?:
    | T
    | {
        host?: T;
        port?: T;
        secure?: T;
        username?: T;
        password?: T;
        passwordEnc?: T;
      };
  imap?:
    | T
    | {
        sameCredentials?: T;
        host?: T;
        port?: T;
        sentFolder?: T;
        username?: T;
        password?: T;
        passwordEnc?: T;
      };
  signature?: T;
  clearStoredCredentials?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}